default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: studio_development
  username: saurabhkr001
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

test:
  <<: *default
  database: studio_test
  username: saurabhkr001
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

cable:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>